dist: bionic
language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "3.5"
  - "3.6"
  - "3.7"
env:  # https://www.djangoproject.com/download/
  - DJANGO=2.2.3
  - DJANGO=2.1.10
install:
  # Build/test dependencies
 - pip install -U pip setuptools
 - pip install -r requirements.txt -r requirements-dev.txt
 - pip install Django==$DJANGO
script:
  - echo -e "DEBUG = True\nSECRET_KEY = 'dummy'" > admin/admin/localsettings.py
  - python dev.py code-quality
